### ISSUE TITLE
Received data len doesn't match len in header

### ISSUE THREAD

**Issue by mint-dewit** [cfra/lenkeng#1]
Hi,

When using a lenkeng 373 V2 I am receiving the error as per title. According to [this blog post](https://blog.danman.eu/reverse-engineering-lenkeng-hdmi-over-ip-extender/) by Danman the length inside the header is malformed and one should "manually parse IP and UDP headers to match correct packets and extract UDP payload with trailing bytes"

But I assume that when you wrote this code you tested this working. So I wonder why Danman's and my extender have malformed packet length but yours apparently doesn't?

**Comment by cfra** [comment]
My extender also exhibits the malformed packet length. If you look at https://github.com/cfra/lenkeng/blob/master/simple_receiver.c#L293 you will see that I use a packet socket operating on layer2 to work around that.

**Comment by mint-dewit** [comment]
My bad, you are working around it. My C skills aren't where I want them to be, honestly.

That makes me wonder, though. What other reasons could invoke that message? If I remove the exception and compile, then I get a distorted output (just like described in the blog post, only the few lines show up correctly)

**Comment by cfra** [comment]
Which exception exactly are you talking about?

**Comment by mint-dewit** [comment]
https://github.com/cfra/lenkeng/blob/master/simple_receiver.c#L280

**Comment by cfra** [comment]
It has been some time since I last worked with this code and I don't have the hardware available at the moment, so unfortunately I cannot give a very detailed answer right now.

Basically, the the length field in the udp header describes how many bytes of payload should be following and the check verifies that this amount of data has been received.

If commenting out this check causes distorted images, I would guess that you are either receiving truncated ethernet frames on the packet socket, or other packets which are not image data are coming in.

To debug this further, you could modify the check to actually log the packet before returning, so that you can figure out which packets are causing this. Otherwise, also just looking at the incoming packets with wireshark might help.

**Comment by mint-dewit** [comment]
Inside the check: the value of `received` is 1052, the value of `(20 + 8 + udp_len)` is 1060

Unlike [this screenshot from the V1](https://blog.danman.eu/wp-content/uploads/2014/01/Screenshot-from-2014-01-24-081915.png) wireshark notes that the total length is 1052 and the data length is 1024. (vs 1044 and 1016 respectively). Also, unlike mentioned screenshot Wireshark does **not** show that there are bytes that are not part of the udp payload.

This almost leads me to believe that the device I have is simply not an original Lenkeng, and instead uses alternative hardware that does not require trailing bytes.

**Comment by cfra** [comment]
Yea, in that case it might be possible that it is indeed sending valid UDP and you could skip the whole raw socket. You could also try if adjusting the check and the call to lkr_handle_chunk by 8 bytes fixes the issue if it is otherwise using the same format.

**Comment by mint-dewit** [comment]
Adjusting https://github.com/cfra/lenkeng/blob/master/simple_receiver.c#L289 to
`	lkr_handle_chunk(lkr, frame_no, chunk_no, last_chunk,
			 r_frame_data, udp_len-12);`
fixed my issue.

Thank you for the guidance!

**Comment by cfra** [comment]
Cool, thanks for the update. Could you possibly send me a short tcpdump of the stream and/or photos/more info on the device? Then I could possibly update the program so that it works out of the box if anybody else uses the same device as you.

**Comment by mint-dewit** [comment]
hey, sorry for the radio silence. I've been unexpectedly busy with work. more info is on my todo-list though!
